const theme = {
  color: {
    primary_base: '#62C0D4',
    primary_light: '',
    primary_dark: '',
    secondary_base: '#2C2C2C',
    secondary_light: '',
    secondary_dark: '#151515',
    black: '',
    grey: '#d7d7d7',
    dark_grey: '#b5b5b5',
    white: '#FFF',
  },
  font_family: {
    primary: '"Nunito", sans-serif',
  },
  font_size: {
    small_m: '10px',
    small: '12px',
    regular_m: '14px',
    regular: '16px',
    medium_m: '18px',
    medium: '20px',
    large: '28px',
    x_large: '36px',
  },
  text_opacity: {
    primary: 1,
    secondary: 0.87,
    disabled: 0.38,
  },
  spacing: [
    '0px',
    '4px',
    '8px',
    '12px',
    '16px',
    '20px',
    '24px',
    '28px',
    '32px',
    '36px',
    '40px',
    '44px',
    '48px',
    '52px',
    '56px',
    '60px',
    '64px',
    '68px',
    '72px',
    '76px',
    '80px',
  ],
};

export default theme;
